version: "3.7"

services:
  backend:
    build: backend
    ports:
      - 8000:8000
    networks: 
      CrimeService: 
        aliases: 
          - backend.docker
    depends_on:
      - redis

  redis: 
    image: redis:alpine 
    ports:
      - "6379:6379" 
    networks: 
      CrimeService: 
        aliases: 
          - redis.docker

  frontend:
    build: frontend
    ports:
      - 8501:8501
    networks: 
      CrimeService: 
        aliases: 
          - frontend.docker
    depends_on:
      - backend

networks:
  CrimeService:
    external: true
