version: "3.7"

services:
  backend:
    build: backend
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis: 
    image: redis:alpine 
    ports:
      - "6379:6379" 

  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
